name: ci

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - app.py
      - requirements.txt
      - templates/index.html
  pull_request:
    paths:
      - Dockerfile
      - app.py
      - requirements.txt
      - templates/index.html
  workflow_dispatch:

env:
  APP: a-flask-of-py
  VERSION: 0.1.0

jobs:
  docker-build-scan-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
